---
title: "p8105_hw3_bs3142"
author: "Bingyu Sun"
date: "10/7/2018"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)

knitr::opts_chunk$set(
  fig.width = 6,
  fig.asp = .6,
  out.width = "90%"
)

theme_set(theme_bw() + theme(legend.position = "bottom"))
```

## Problem 1

#### Section 1: Data import

```{r import brfss data}
library(p8105.datasets)
data(brfss_smart2010)
```

#### Section 2: Data Manipulation

```{r}
brfss_data =
  brfss_smart2010 %>%
  janitor::clean_names() %>%
  filter(topic == "Overall Health") %>%
  select(-(class:question), -sample_size, -(confidence_limit_low:geo_location)) %>%
  mutate(response = factor(response))

str(brfss_data)
```

#### Section 3: Q & A

**1. In 2002, which states were observed at 7 locations?**

```{r}
brfss_data %>%
  filter(year == 2002) %>%
  group_by(locationabbr) %>%
  summarize(n = n_distinct(locationdesc))
```

**CT, FL, NC** were observed at 7 locations.

**2. Make a “spaghetti plot” that shows the number of observations in each state from 2002 to 2010.**

```{r}

```

